format = '$all'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol ($version)]($style)\]'
symbol = ''

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[sudo]
disabled = false
format = '\[[$symbol]($style)\]'
symbol = '󰄿'

[username]
format = '\[[$user]($style)\]'

[cmd_duration]
format = ' 󰚭[$duration]($style)'
