import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]

normal.family = "FiraCode Nerd Font"
normal.style = "Bold"

size = 16

[window]

decorations = "None"

[[keyboard.bindings]]
key = "Slash"
mods = "Control"
chars = "\u001f"  # Sends ASCII 0x1F, which is <C-_>
